ecomerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.indexPage, name = 'index'),
    path('results/', views.resultsPage, name = 'results'),
    path('book/<str:bk_isbn>/', views.bookPage, name = 'book'),
    path('mostsellers/', views.mostSellersPage, name = 'mostsellers'),
    path('forkids/', views.forKidsPage, name = 'forkids'),
    path('foradults/', views.forAdultsPage, name = 'foradults'),
    path('login/', views.loginPage, name = 'login'),
    path('signup/', views.signupPage, name = 'signup'),
    path('logout/', views.logoutPage, name = 'logout'),
]

website/models.py
from django.db import models
from django.utils.text import slugify

# add editor and age attributs \

# Create your models here.

class Book(models.Model):
    isbn = models.CharField(max_length = 30, primary_key = True)
    title = models.CharField(max_length = 100)
    writter = models.CharField(max_length = 100)
    publication_date = models.DateField()
    description = models.CharField(max_length = 500)
    download_number = models.IntegerField(default = 0)
    genre = models.CharField(max_length = 20)
    publisher = models.CharField(max_length = 50)
    age = models.CharField(max_length = 10)
    photo = models.FileField(upload_to = 'website/bookphotos/')
    file = models.FileField(upload_to = 'website/bookfiles/')
    price = models.IntegerField(default = 0)

    def __str__(self):
        return self.title
        
        
class User(models.Model):
    username = models.CharField(max_length = 100)
    email = models.EmailField()
    password = models.CharField(max_length = 10)
    address = models.CharField(max_length = 150)
    phone_number = models.CharField(max_length = 20)
    login_date = models.DateField()
    my_books = models.ManyToManyField(Book, through = 'UserCart')
    
    def __str__(self):
        return self.username
        

class UserComment(models.Model):
    user_id = models.ForeignKey(User, on_delete = models.CASCADE)
    book_isbn = models.ForeignKey(Book, on_delete = models.CASCADE)
    comment = models.CharField(max_length = 500)
    comment_date = models.DateField()
    
    def __str__(self):
        return self.id
        
        
class UserCart(models.Model):
    user_id = models.ForeignKey(User, on_delete = models.CASCADE)
    book_isbn = models.ForeignKey(Book, on_delete = models.CASCADE)
    buyed = models.BooleanField(default = False)
    buy_date = models.DateField()
    
    def __str__(self):
        return self.id

website/views.py
from django.shortcuts import render,redirect
from .models import Book
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout, login
from django.contrib import messages

# Create your views here.



def indexPage(request):
    return render(
        request,
        'website/index.html',
        {'newbooks':Book.objects.all()[:]}
    )

def resultsPage(request):
    return render(
        request,
        'website/results.html',
        {'results':Book.objects.filter(title__contains = request.POST.get('search'))}
    )

def bookPage(request, bk_isbn):
    return render(
        request,
        'website/book.html',
        {'book':Book.objects.get(isbn = bk_isbn)}
    )

def mostSellersPage(request):
    return render(
        request,
        'website/mostsellers.html',
        {'books':Book.objects.order_by('download_number')}
    )

def forKidsPage(request):
    return render(
        request,
        'website/forkids.html',
        {'books':Book.objects.filter(genre = 'kids')}
    )

def forAdultsPage(request):
    return render(
        request,
        'website/foradults.html',
        {'books':Book.objects.filter(age = '18')}
    )

def loginPage(request):
    if request.method == 'POST':
        user = authenticate(
            request,
            username = request.POST.get('username'),
            password = request.POST.get('password')
        )

        if user is not None:
            print(user.is_authenticated)
            login(request, user)

            return HttpResponseRedirect(reverse('website:index'))
        else:
            return render(request,'website/login.html',{'error':'User does not exist'})
    else:
        return render(
            request,
            'website/login.html',
            {}
        )

def signupPage(request):
    if request.method == 'POST':
        user = User.objects.create_user(
                username = request.POST.get('username'),
                password = request.POST.get('password'),
                first_name = request.POST.get('firstname'),
                last_name = request.POST.get('lastname'),
                email = request.POST.get('email')
        )

        user.save()

        return HttpResponseRedirect(reverse('website:index'))
    else:
        return render(
            request,
            'website/signup.html',
            {}
        )

def logoutPage(request):
    logout(request)

    return HttpResponseRedirect(reverse('website:login'))


templates/website/base.html
<!DOCTYPE html>
{% load static %}


<html>
	<head>
		<meta charset='utf-8'>

		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

		<title>
			{% block titlepage %}
			{% endblock %}
		</title>
	</head>

	<body>
		<header>
			<a href="{% url 'website:index' %}"><h2 class="b_item">BookStore</h2></a>

			<div id="divsearch">
                <form method='POST' action="{% url 'website:results' %}" class="b_item">
                    {% csrf_token %}
                    <button type="submit" class="btnheader"><i class="fa fa-search"></i></button>
                    <input type='text' placeholder='Search' class="s_form" name="search">
                </form>
            </div>

			{% if user.is_authenticated %}
				<span style="font-weight:bold;">Hello {{ user.username }}</span>
				<a href="{% url 'website:logout' %}">Logout</a>
			{% endif %}

			<span id="productsnumber">0</span>
			<a href=""><img src="{% static 'images/website/cart.png' %}" class="h_icon b_item"></a>
			<a href="{% url 'website:login' %}"><img src="{% static 'images/website/login.png' %}" class="h_icon b_item"></a>


			<nav>
				<a href="">Offers</a>
				<a href="{% url 'website:mostsellers' %}">The most seller</a>
				<a href="{% url 'website:forkids' %}">For kids</a>
				<a href="{% url 'website:foradults' %}">For adults</a>
			</nav>
		</header>

		<div id="container">
			{% block sbjct_container %}
			{% endblock %}
		</div>


		<footer>
			<h3>BookStore. All rights reserverd</h3>
		</footer>

	</body>
</html>

templates/website/book.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% load static %}

{% block sbjct_container %}
        <div class="bk_info">
                <img src="{{ MEDIA_URL }}{{ book.photo }}" id="bkphoto"/>
        </div>

        <div class="bk_info bk_info2">
                <h2>{{ book.title }}</h2>

                {% if user.is_authenticated %}
                        <a href="{{ MEDIA_URL }}{{ book.file }}" download><button>Download</button></a><br/>
                {% else %}
                        <h4>Login to download books.</h4>
                {% endif %}

                Price: $${{ book.price }}<br/>
                Writter:{{ book.writter }}<br/>
                Publisher: {{ book.publisher }}<br/>
                Date of publication: {{ book.publication_date }}<br/>
                Genre: {{ book.genre }}<br/>
                Number of downloads: {{ book.download_number }}<br/>
                Age: {{ book.age }}<br/>
                Description: {{ book.description }}<br/>
        </div>
{% endblock %}


templates/website/foradults.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% load static %}

{% block titlepage %}
    For adults
{% endblock %}

{% block sbjct_container %}
    <h2 class="titlepage">For adults</h2>

    <div class="books">
        {% for nb in books %}
            <div class="displaybook">
              <a href="{% url 'website:book' nb.isbn %}"><img src="{{ MEDIA_URL }}{{ nb.photo }}" class="bookimage" /></a>

               <h3 class="booktitle">{{ nb.title }}</h3>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/website/forkids.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% load static %}

{% block titlepage %}
    For kids
{% endblock %}

{% block sbjct_container %}
    <h2 class="titlepage">For kids</h2>

    <div class="books">
        {% for nb in books %}
            <div class="displaybook">
              <a href="{% url 'website:book' nb.isbn %}"><img src="{{ MEDIA_URL }}{{ nb.photo }}" class="bookimage" /></a>

               <h3 class="booktitle">{{ nb.title }}</h3>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/website/index.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% load static %}

{% block sbjct_container %}
     <div class="books">
        {% for nb in newbooks %}
            <div class="displaybook">
              <a href="{% url 'website:book' nb.isbn %}"><img src="{{ MEDIA_URL }}{{ nb.photo }}" class="bookimage" /></a>

               <h3 class="booktitle">{{ nb.title }}</h3>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/website/login.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>Login</title>
</head>

<body>

    <div class="logsigdiv">
        <img src="{% static 'images/website/login.png' %}" class="logsigimg">

        {% if error %}
            <h4 color="#ff0011" id="logerror">{{ error }}!!</h4>
        {% endif %}

        <form method="POST" action="">
            {% csrf_token %}

            <span for="usernamefield">Username</span><br/><br/>
            <input type="text" name="username" id="usernamefield"/><br/><br/><br/>

            <span for="passwordfield">Password</span><br/><br/>
            <input type="password" name="password" id="passwordfield"/><br/><br/><br/>


            <input type="submit" value="submit"/>
        </form>

        <a href="{% url 'website:index' %}">Index</a> <a href="{% url 'website:signup' %}">Sign up</a>

    </div>

</body>
</html>

templates/website/mostsellers.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% load static %}

{% block titlepage %}
    The most sellers
{% endblock %}

{% block sbjct_container %}
    <h2 class="titlepage">The most sellers</h2>

     <div class="books">
        {% for nb in books %}
            <div class="displaybook">
              <a href="{% url 'website:book' nb.isbn %}"><img src="{{ MEDIA_URL }}{{ nb.photo }}" class="bookimage" /></a>

               <h3 class="booktitle">{{ nb.title }}</h3>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/website/results.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% load static %}

{% block sbjct_container %}
        <div id="filter">

            <h2>Filter div</h2>

            <form method="" action="">
                {% csrf_token %}

                <label>Name:</label>
                <input type="text" name="bkname" placeholder="Type book name here">

                <br><br>

                <label>Gender:</label>
                <select name="bkgender">
                    <option value="romance">Romance</option>
                    <option value="fiction">Fiction</option>
                    <option value="sensual">Sensual</option>
                </select>

                <br><br>

                <label>Date:</label>
                <input type="date" name="bkdate">

                <br><br>

                <input type="submit" value="submit">

            </form>

        </div>

        <div id="results">

            <h2 class="titlepage">Results</h2>

            {% for re in results %}
                <div class="bksearch">
                    <a href="{% url 'website:book' re.isbn %}"><img src="{{ MEDIA_URL }}{{ re.photo }}"/></a>

                    <h3>{{ re.title }}</h3>
                </div>
            {% endfor %}

        </div>
{% endblock %}




templates/website/signup.html
<!DOCTYPE html>
{% load static %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>Sign Up</title>
</head>
<body>

    <div class="logsigdiv">
        <h2 class="titlepage">Sign Up</h2>
        <h3 id="errormessage">{{ error }}</h3>
        <form method="POST" action="{% url 'website:signup' %}">
            {% csrf_token %}

            <label>Email:</label>
            <input type="email" name="email"/><br/<br/><br/><br/>

            <label>Password:</label>
            <input type="password" name="password"/><br/><br/><br/>

            <label>First name:</label>
            <input type="text" name="firstname"/><br/><br/><br/>

            <label>Last name:</label>
            <input type="text" name="lastname"/><br/><br/><br/>

            <label>Username:</label>
            <input type="text" name="username"/><br/><br/><br/>

            <input type="submit" value="submit"/>
        </form>
    </div>

</body>
</html>
